### ISSUE TITLE
Waiting for efi for Ventura

### ISSUE THREAD

**Issue by AlsheikhBasha** [mahronid/thinkpad-e480-hackintosh#1]
Ota update didn't work for me on this config when trying ventura beta through ota beta updates

**Comment by mahronid** [comment]
> Ota update didn't work for me on this config when trying ventura beta through ota beta updates

Hi, working on it :)

**Comment by mahronid** [comment]
> 

EFI has been updated to OpenCore 0.9.2 support macOS Ventura.
